Chores
nats-io/spring-nats pull request #33
Opened 2023-07-30 22:55 UTC by lyca

Update versions while still keeping it compatible with Java 8 (Spring Boot >= 3.x needs Java 17).

2023-07-31 05:45 UTC, YunaBraska approved these changes

2023-11-14 14:06 UTC, scottf requested changes
2.17.1 instead of 2.16.13

2023-11-14 14:06 UTC, scottf commented on README.md
> +    <version>2.16.13</version>
What about 2.17.1?

2023-11-14 14:06 UTC, scottf commented on nats-spring-boot-starter/pom.xml
> +            <version>2.16.13</version>
What about 2.17.1?

2023-11-14 14:06 UTC, scottf commented on nats-spring-cloud-stream-binder/pom.xml
> +            <version>2.16.13</version>
What about 2.17.1?

2023-11-14 14:06 UTC, scottf commented on nats-spring/pom.xml
> +            <version>2.16.13</version>
What about 2.17.1?

2023-11-14 14:09 UTC, scottf commented
Is there something specific about 2.16.13 that it should be used instead of 2.17.1?

2023-11-14 15:31 UTC, merged